export TERMINAL="alacritty"
export BROWSER="firefox"
export BROWSER_ALTERNATIVE="chromium-browser"
export BROWSER_PRIVATE="brave-browser --incognito"
export FILE_MANAGER="krusader"
export IDE="code"
export SYSTEM_SETTINGS="systemsettings5"