FROM {{ item.image }}

RUN echo '%user    ALL=(ALL)   NOPASSWD: ALL' >> /etc/sudoers
RUN useradd -m user

USER user

RUN mkdir -p /home/user/.setup/dotfiles/vscode/
RUN echo '{"": ""}' > /home/user/.setup/dotfiles/vscode/settings.json
RUN echo '[]'       > /home/user/.setup/dotfiles/vscode/keybindings.json

WORKDIR /home/user

