packages:
  - name: alacritty
    description: Terminal-Emulator written in rust
    package_name:
      Fedora: alacritty
  - name: zsh
    description:  zsh shell
    package_name:
      Fedora: zsh
  - name: tmux
    description:  Terminal system monitor
    package_name:
      Fedora: htop
  - name: vim
    description:  Text Editor
    package_name:
      Fedora: vim
  - name: Krusader
    description:  Total Commander like file manager
    package_name:
      Fedora: krusader