- name: Make variables
  block:
    - set_fact:
        dotfile_config_dir: "{{ dotfile.path | replace(dotfile_dir, '') }}"
    - set_fact:
        dotfile_config_dir_name: "{{ dotfile_config_dir.split('/')[1] }}"
    - set_fact:
        dotfile_relative_path: "{{ dotfile_config_dir.split('/')[2:] | join('/') }}"
    - set_fact:
        dotfile_target_path: "{{ target_dir }}/{{ dotfile_relative_path }}"
    - set_fact:
        dotfile_target_backup_path: "{{ dotfile_target_path }}.bak"

- name: Backup and symlink if whitelisted
  block:
    - name: Backup dotfile
      include_tasks: backup_existing_dotfile.yml

    - name: Make directory
      file:
        path: "{{ dotfile_target_path | dirname}}"
        state: directory

    - name: Symlink dotfile
      include_tasks: symlink_dotfile.yml
  when: ( (not dotfile_config_dir_name in blacklist) and ((dotfile_config_dir_name in whitelist) or (whitelist is undefined)) )