- name: Search for dotfiles
  find:
    path: ["{{ dotfile_dir }}"]
    recurse: yes
    hidden: yes
  register: dotfiles

- name: Handle dotfiles
  include_tasks: handle_dotfile.yml
  loop_control:
    loop_var: dotfile
  loop:  "{{ dotfiles.files }}"