---
- name: Install VSCode
  block:
    - name: Import key
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Copy .repo file
      ansible.builtin.copy:
        src: vscode.repo
        dest: /etc/yum.repos.d/vscode.repo
        owner: root
        group: root
        mode: "0644"

    - name: Install code
      ansible.builtin.dnf:
        name: code
        state: present
        update_cache: yes

  become: yes

- name: Install VSCode extensions
  block:
    - name: Read extensions file
      ansible.builtin.include_vars:
        file: extensions.yml
        name: vscode_extensions

    - name: Install VSCode extension
      ansible.builtin.command: "code --install-extension {{ item.extension_name }}"
      register: result
      loop: "{{ vscode_extensions.extensions }}"
      changed_when: result.stdout is not search('is already installed.')

  become: no
