---
- name: Ensure 'keyd_dir' basedir exists
  ansible.builtin.file:
    name: "{{ keyd_dir | dirname }}"
    state: directory

- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - git
    - gcc
    - make
  become: yes

- name: Clone keyd repo
  ansible.builtin.git:
    repo: "{{ keyd_repo }}"
    dest: "{{ keyd_dir }}"
    version: master
  register: git_result

- name: Build keyd
  community.general.make:
    chdir: "{{ keyd_dir }}"
  when: git_result['changed']

- name: Install keyd
  community.general.make:
    chdir: "{{ keyd_dir }}"
    target: install
  when: git_result['changed']
  become: yes

- name: Copy config
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/keyd/default.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Enable keyd service
  ansible.builtin.systemd:
    name: keyd
    enabled: yes
  when: keyd_enable
  become: yes
