- name: Initial setup
  hosts: localhost
  connection: local

  roles:
  - role: initial_setup

  become: yes
  tags: [initial, sudo]

- name: Install packages
  hosts: localhost
  connection: local

  pre_tasks:
  - name: Load package config
    include_vars:
      file: vars/packages.yml
      name: package_config

  roles:
  - role: packages
    vars:
      packages: "{{ package_config.packages }}"
  
  become: yes
  tags: [sudo]

- name: Link dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: dotfiles
      vars:
        blacklist: []

- name: KDE Setup
  hosts: localhost
  connection: local

  roles:
  - kde
  
  tags: [initial, kde]

- name: VSCode Extensions
  hosts: localhost
  connection: local

  tasks:
  - name: Read extensions file
    include_vars:
      file: vscode_extensions.yml
      name: vscode_extensions

  - name: Install VSCode extension
    shell: "code --install-extension {{ item.extension_name }}"
    register: result
    loop: "{{ vscode_extensions.extensions }}"
    changed_when: result.stdout is not search('is already installed.')
  
  tags: [vscode, never]
