- name: Initial setup
  hosts: localhost
  connection: local

  roles:
  - role: initial_setup

  become: yes
  tags: [initial, sudo]

- name: Install packages
  hosts: localhost
  connection: local

  pre_tasks:
  - name: Load package config
    include_vars:
      file: vars/packages.yml
      name: package_config

  roles:
  - role: packages
    vars:
      packages: "{{ package_config.packages }}"
  
  become: yes
  tags: [sudo, packages]

- name: Link dotfiles
  hosts: localhost
  connection: local

  vars:
    dotfile_dir: "$HOME/.setup/dotfiles"
    target_dir: "$HOME"
    dotfiles:
      - bash
      - fish
      - git
      - jumpapp
      - kde
      - nvim
      - tmux
      - xmodmap

  tasks:
    - name: Install stow
      package:
        name: stow
        state: present
      become: yes

    - name: Run stow
      shell: "stow -d {{ dotfile_dir }} -t {{ target_dir }} -S {{ item }}"
      loop: "{{ dotfiles }}"

  tags: [sudo, dotfiles]

- name: Setup Syncthing
  hosts: localhost
  connection: local

  tasks:
    - name: Install syncthing
      package:
        name: syncthing
        state: present
      become: yes

    - name: Kick-off syncthing
      systemd:
        name: syncthing
        scope: user
        state: started
        enabled: yes

  tags: [sudo, syncthing]

- name: KDE Setup
  hosts: localhost
  connection: local

  roles:
  - kde
  
  tags: [initial, kde]

- name: VSCode Extensions
  hosts: localhost
  connection: local

  roles:
    - vscode
  
  become: yes

  tags: [sudo, vscode, never]
