- name: Initial setup
  hosts: localhost
  connection: local

  roles:
  - role: initial_setup

  tags: [initial]

- name: Link dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: dotfiles
      vars:
        blacklist: []
