- name: Initial setup
  hosts: localhost
  connection: local

  roles:
  - role: initial_setup

  become: yes
  tags: [initial, sudo]

- name: Install packages
  hosts: localhost
  connection: local

  pre_tasks:
  - name: Load package config
    include_vars:
      file: vars/packages.yml
      name: package_config

  roles:
  - role: packages
    vars:
      packages: "{{ package_config.packages }}"
  
  become: yes
  tags: [sudo]

- name: Link dotfiles
  hosts: localhost
  connection: local

  roles:
    - role: dotfiles
      vars:
        blacklist: []
